### PR TITLE
feat: interactive tree implementation. 

### PR DESCRIPTION
**Pull request by endalkh**
**What is done**
- Create an interactive tree design
- add nodes as a child and as a root. 
- Update nodes 
- Delete nodes
- Add permission and restrict the node that can modify/delete it. 
- Protect node from deletion if the node has at least one child. 
- move the node using Drag and drop. 
- Update a database model and add a relationship **Product** -> **ProductTree** -> **ProductArea**
- Register and enable the filter on the admin site. 
- Add product detail page to add more details of product Area, More details like video and longer description.

### CODE REVIEW

**Comment by adrianmcphee** [comment]
Thanks @endalkh !

@dogukanteber pls review

**Comment by dogukanteber** [comment]
Hi @endalkh. Thank you for your work!

I can't see a button for creating and deleting a new product area. In the ux-prototype repository, we have something like this:

Screenshot 2024-03-26 at 15 03 17

When I try to update the product area, I cannot type anything in the fields. Also, I don't think we need to get `video_name` and `video_duration` information.

It also seems like the drag-and-drop doesn't work.

Can you fix those and update the PR?

**Comment by endalkh** [comment]
> Hi @endalkh. Thank you for your work!
> 
> I can't see a button for creating and deleting a new product area. In the ux-prototype repository, we have something like this:
> 
> Screenshot 2024-03-26 at 15 03 17
> When I try to update the product area, I cannot type anything in the fields. Also, I don't think we need to get `video_name` and `video_duration` information.
> 
> It also seems like the drag-and-drop doesn't work.
> 
> Can you fix those and update the PR?

Hey @dogukanteber, Thank you for the review, We added the permission, to modify the nodes, you have to be Admin or Manager on ProductRoleAssignment for that specific product.

**Review by dogukanteber — APPROVED** [review]

**Comment by endalkh** [comment]
> Okay, now I see it. I can't see anything wrong. Everything seems to be working. Thank you for your work 🚀

Thank you!

**Pull request merged**
