### PR TITLE
feat: add bug feature

### PR DESCRIPTION
**Pull request by oasissolution**
Add bug feature

### CODE REVIEW

**Comment by dogukanteber** [comment]
Can you also add tests @oasissolution?

**Comment by oasissolution** [comment]
There test errors in CreateChallengeViewTestCase. Could you please fix it?

**Comment by oasissolution** [comment]
Hi @dogukanteber . 
There is Unittest error in TalentAppFunctionBasedViewsTest.
Can you check it?

**Comment by oasissolution** [comment]
Hi @dogukanteber . It seems that you have removed pagination in Productlistview. I couldn't passed the test due to this one.
Could you guide me what should I do next? Add pagination or adjust test properly?
Thanks.

**Comment by dogukanteber** [comment]
Thank you for your contribution @oasissolution! We greatly appreciate it. The code looks good to me. We can merge it 🚀

**Comment by oasissolution** [comment]
> Thank you for your contribution @oasissolution! We greatly appreciate it. The code looks good to me. We can merge it 🚀

Thanks.

**Pull request merged**
